### ISSUE TITLE
What do the italics mean in the README table?

### ISSUE THREAD

**Issue by 17cupsofcoffee** [TomGillen/ecs_bench_suite#4]
Noticed that there are some entries in the comparison table in the README that are bold, and some that are in italics.

It seems fairly obvious that bold means 'best', but I can't work out whether there's a specific meaning to the italics or if they're just also meant to be bold (they all seem to be ones that are within the varience threshold of the winning result). If the former, then maybe this should be clarified; if the latter I can submit a PR to make them consistent.

**Comment by TomGillen** [comment]
The italics are just results that are so close to the best result that they are within the run to run noise. It should probably either be clarified or removed.

**Comment by Ralith** [comment]
If they mean "approximately equal to best", perhaps they should be rendered in the same way as the best?

**Comment by 17cupsofcoffee** [comment]
Fixed in #7.
